# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
on: ["pull_request"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: echo 'feature' > feature.txt
      - run: git status
      - uses: actions/upload-artifact@v4
        with:
          name: feature-thingy
          path: feature.txt
      - uses: actions/checkout@v6
        with: { ref: main }
      - run: git status
      - uses: actions/download-artifact@v4
        with:
          name: feature-thingy
          path: feature.txt
      - run: git status
      - run: echo 'main' > main.txt
      - run: git status
      - uses: actions/upload-artifact@v4
        with:
          name: main-thingy
          path: main.txt
      - uses: actions/checkout@v6
      - run: git status
      - uses: actions/download-artifact@v4
        with:
          name: feature-thingy
          path: feature.txt
      - uses: actions/download-artifact@v4
        with:
          name: main-thingy
          path: main.txt
      - run: git status
