# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
on: ["pull_request"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: integration_tests/run_test.sh
